name: Build and Release Binaries (Linux)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Download IBM Semeru Runtime (Linux x64)
        shell: bash
        run: |
          curl -L \
            -o semeru.tar.gz \
            https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.9%2B10_openj9-0.56.0/ibm-semeru-open-jre_x64_linux_21.0.9_10_openj9-0.56.0.tar.gz

          mkdir tempjre
          tar -xzf semeru.tar.gz -C tempjre

          mkdir jre
          mv tempjre/*/* jre
          rm -rf tempjre semeru.tar.gz

      - name: Build and package (Linux App Image)
        run: mvn package jpackage:jpackage@linux

      - name: Create tar.gz from output/
        run: |
          cd output
          tar -czf ../nautilus-${{ github.ref_name }}-linux.tar.gz *
          cd ..

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: nautilus-${{ github.ref_name }}-linux.tar.gz
